version: "3.8"

services:

  balancer:
    container_name: balancer
    build:
      context: ./balancer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./balancer/app:/app
    environment:
      - DOCKER_APP="true"
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_RESET=false

  front:
    container_name: front
    build:
      context: ./balancer-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./balancer-ui:/app
    depends_on:
      - balancer
    environment:
      - REACT_APP_DOCKER_APP=true
