version: "3.8"

services:
  front:
    container_name: front
    build:
      context: ./balancer-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    depends_on:
      - balancer
    environment:
      - DOCKER_APP="true"

  balancer:
    container_name: balancer
    build:
      context: ./balancer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-app:/app
